void createBoard (){
  line(COLUMN_WIDTH, 0, COLUMN_WIDTH, SIZE);
  line(COLUMN_WIDTH_DOUBLED, 0, COLUMN_WIDTH_DOUBLED, SIZE);
  line(0, COLUMN_WIDTH, SIZE, COLUMN_WIDTH);
  line(0, COLUMN_WIDTH_DOUBLED, SIZE,COLUMN_WIDTH_DOUBLED);
}
void drawX() {
}
